package incremental

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/harshsharma/code-review-graph-go/internal/config"
)

var safeGitRef = regexp.MustCompile(`^[A-Za-z0-9_.~^/@{}\-]+$`)

func gitTimeout() time.Duration {
	return time.Duration(config.GitTimeout) * time.Second
}

// FindRepoRoot walks up from start to find the nearest .git directory.
func FindRepoRoot(start string) string {
	if start == "" {
		start, _ = os.Getwd()
	}
	current, _ := filepath.Abs(start)
	for {
		if _, err := os.Stat(filepath.Join(current, ".git")); err == nil {
			return current
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
		current = parent
	}
	return ""
}

// FindProjectRoot resolves the project root with CRG_REPO_ROOT override.
func FindProjectRoot(start string) string {
	if override := config.RepoRootOverride(); override != "" {
		abs, err := filepath.Abs(override)
		if err == nil {
			if _, err := os.Stat(abs); err == nil {
				return abs
			}
		}
	}
	if root := FindRepoRoot(start); root != "" {
		return root
	}
	if start != "" {
		return start
	}
	cwd, _ := os.Getwd()
	return cwd
}

// GetDataDir returns the graph data directory for a repo.
func GetDataDir(repoRoot string) string {
	if override := config.DataDirOverride(); override != "" {
		abs, _ := filepath.Abs(override)
		_ = os.MkdirAll(abs, 0o755)
		writeInnerGitignore(abs)
		return abs
	}
	dataDir := filepath.Join(repoRoot, ".code-review-graph")
	_ = os.MkdirAll(dataDir, 0o755)
	writeInnerGitignore(dataDir)
	return dataDir
}

// GetDBPath returns the database path, handling legacy migration.
func GetDBPath(repoRoot string) string {
	crgDir := GetDataDir(repoRoot)
	newDB := filepath.Join(crgDir, "graph.db")

	legacyDB := filepath.Join(repoRoot, ".code-review-graph.db")
	if _, err := os.Stat(legacyDB); err == nil {
		if _, err := os.Stat(newDB); os.IsNotExist(err) {
			_ = os.Rename(legacyDB, newDB)
		}
	}
	for _, suffix := range []string{"-wal", "-shm", "-journal"} {
		side := legacyDB + suffix
		_ = os.Remove(side)
	}

	return newDB
}

func writeInnerGitignore(dir string) {
	gi := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(gi); err == nil {
		return
	}
	_ = os.WriteFile(gi, []byte("# Auto-generated by code-review-graph\n*\n"), 0o644)
}

// GetChangedFiles returns files changed since the given git ref.
func GetChangedFiles(repoRoot, base string) ([]string, error) {
	if !safeGitRef.MatchString(base) {
		slog.Warn("invalid git ref rejected", "ref", base)
		return nil, nil
	}

	ctx, cancel := context.WithTimeout(context.Background(), gitTimeout())
	defer cancel()

	cmd := exec.CommandContext(ctx, "git", "diff", "--name-only", base, "--")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		// Fallback: try diff against cached
		cmd2 := exec.CommandContext(ctx, "git", "diff", "--name-only", "--cached")
		cmd2.Dir = repoRoot
		out, err = cmd2.Output()
		if err != nil {
			return nil, nil
		}
	}

	return splitLines(string(out)), nil
}

// GetStagedAndUnstaged returns all modified files (staged + unstaged + untracked).
func GetStagedAndUnstaged(repoRoot string) ([]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), gitTimeout())
	defer cancel()

	cmd := exec.CommandContext(ctx, "git", "status", "--porcelain")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return nil, nil
	}

	var files []string
	for _, line := range strings.Split(string(out), "\n") {
		if len(line) < 4 {
			continue
		}
		entry := strings.TrimSpace(line[3:])
		if idx := strings.Index(entry, " -> "); idx >= 0 {
			entry = entry[idx+4:]
		}
		if entry != "" {
			files = append(files, entry)
		}
	}
	return files, nil
}

// GetAllTrackedFiles returns all git-tracked files.
func GetAllTrackedFiles(repoRoot string) ([]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), gitTimeout())
	defer cancel()

	recurse := os.Getenv("CRG_RECURSE_SUBMODULES")
	args := []string{"ls-files"}
	if strings.EqualFold(recurse, "1") || strings.EqualFold(recurse, "true") {
		args = append(args, "--recurse-submodules")
	}

	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return nil, nil
	}

	return splitLines(string(out)), nil
}

// GitBranchInfo returns (branch, sha) for the current repo state.
func GitBranchInfo(repoRoot string) (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), gitTimeout())
	defer cancel()

	var branch, sha string

	cmd := exec.CommandContext(ctx, "git", "rev-parse", "--abbrev-ref", "HEAD")
	cmd.Dir = repoRoot
	if out, err := cmd.Output(); err == nil {
		branch = strings.TrimSpace(string(out))
	}

	cmd2 := exec.CommandContext(ctx, "git", "rev-parse", "HEAD")
	cmd2.Dir = repoRoot
	if out, err := cmd2.Output(); err == nil {
		sha = strings.TrimSpace(string(out))
	}

	return branch, sha
}

// EnsureGitignore ensures the repo .gitignore excludes .code-review-graph/.
func EnsureGitignore(repoRoot string) (string, error) {
	giPath := filepath.Join(repoRoot, ".gitignore")
	existing, err := os.ReadFile(giPath)
	if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("reading .gitignore: %w", err)
	}

	content := string(existing)
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if line == ".code-review-graph" || strings.HasPrefix(line, ".code-review-graph/") {
			return "already-present", nil
		}
	}

	block := "\n# Added by code-review-graph\n.code-review-graph/\n"
	if len(content) > 0 && !strings.HasSuffix(content, "\n") {
		block = "\n" + block
	}

	if err := os.WriteFile(giPath, []byte(content+block), 0o644); err != nil {
		return "", fmt.Errorf("writing .gitignore: %w", err)
	}

	if len(existing) == 0 {
		return "created", nil
	}
	return "updated", nil
}

func splitLines(s string) []string {
	var lines []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			lines = append(lines, line)
		}
	}
	return lines
}
