package parser

var ExtensionToLanguage = map[string]string{
	".py":    "python",
	".js":    "javascript",
	".jsx":   "javascript",
	".ts":    "typescript",
	".tsx":   "tsx",
	".go":    "go",
	".rs":    "rust",
	".java":  "java",
	".cs":    "csharp",
	".rb":    "ruby",
	".cpp":   "cpp",
	".cc":    "cpp",
	".cxx":   "cpp",
	".c":     "c",
	".h":     "c",
	".hpp":   "cpp",
	".kt":    "kotlin",
	".swift": "swift",
	".php":   "php",
	".scala": "scala",
	".sol":   "solidity",
	".vue":   "vue",
	".dart":  "dart",
	".r":     "r",
	".mjs":   "javascript",
	".astro": "typescript",
	".pl":    "perl",
	".pm":    "perl",
	".lua":   "lua",
	".sh":    "bash",
	".bash":  "bash",
	".zsh":   "bash",
	".ex":    "elixir",
	".exs":   "elixir",
}

var ClassTypes = map[string][]string{
	"python":     {"class_definition"},
	"javascript": {"class_declaration", "class"},
	"typescript": {"class_declaration", "class"},
	"tsx":        {"class_declaration", "class"},
	"go":         {"type_declaration"},
	"rust":       {"struct_item", "enum_item", "impl_item"},
	"java":       {"class_declaration", "interface_declaration", "enum_declaration"},
	"c":          {"struct_specifier", "type_definition"},
	"cpp":        {"class_specifier", "struct_specifier"},
	"csharp":     {"class_declaration", "interface_declaration", "enum_declaration", "struct_declaration"},
	"ruby":       {"class", "module"},
	"kotlin":     {"class_declaration", "object_declaration"},
	"swift":      {"class_declaration", "struct_declaration", "protocol_declaration"},
	"php":        {"class_declaration", "interface_declaration"},
	"scala":      {"class_definition", "trait_definition", "object_definition", "enum_definition"},
	"dart":       {"class_definition", "mixin_declaration", "enum_declaration"},
}

var FunctionTypes = map[string][]string{
	"python":     {"function_definition"},
	"javascript": {"function_declaration", "method_definition", "arrow_function"},
	"typescript": {"function_declaration", "method_definition", "arrow_function"},
	"tsx":        {"function_declaration", "method_definition", "arrow_function"},
	"go":         {"function_declaration", "method_declaration"},
	"rust":       {"function_item"},
	"java":       {"method_declaration", "constructor_declaration"},
	"c":          {"function_definition"},
	"cpp":        {"function_definition"},
	"csharp":     {"method_declaration", "constructor_declaration"},
	"ruby":       {"method", "singleton_method"},
	"kotlin":     {"function_declaration"},
	"swift":      {"function_declaration"},
	"php":        {"function_definition", "method_declaration"},
	"scala":      {"function_definition", "function_declaration"},
	"dart":       {"function_signature"},
	"lua":        {"function_declaration"},
	"bash":       {"function_definition"},
}

var ImportTypes = map[string][]string{
	"python":     {"import_statement", "import_from_statement"},
	"javascript": {"import_statement"},
	"typescript": {"import_statement"},
	"tsx":        {"import_statement"},
	"go":         {"import_declaration"},
	"rust":       {"use_declaration"},
	"java":       {"import_declaration"},
	"c":          {"preproc_include"},
	"cpp":        {"preproc_include"},
	"csharp":     {"using_directive"},
	"ruby":       {"call"},
	"kotlin":     {"import_header"},
	"swift":      {"import_declaration"},
	"php":        {"namespace_use_declaration"},
	"scala":      {"import_declaration"},
	"dart":       {"import_or_export"},
	"lua":        {"function_call"},
	"bash":       {"command"},
}

var TestPrefixes = map[string][]string{
	"python":     {"test_", "Test"},
	"javascript": {"test", "it(", "describe("},
	"typescript": {"test", "it(", "describe("},
	"tsx":        {"test", "it(", "describe("},
	"go":         {"Test", "Benchmark"},
	"rust":       {"test_"},
	"java":       {"test"},
	"csharp":     {"Test"},
	"ruby":       {"test_"},
	"kotlin":     {"test"},
	"swift":      {"test"},
	"php":        {"test"},
}
